### PR TITLE
Add reasoning fields.

### PR DESCRIPTION
**Pull request by eugenk**
This is the ontohub-backend-part of https://github.com/ontohub/ontohub-models/pull/154 and https://github.com/spechub/Hets/pull/1836. It only adjusts the GraphQL schema.

### CODE REVIEW

**Comment by eugenk** [comment]
I have no idea why Travis fails when recreating the database all of the sudden...

**Comment by phyrog** [comment]
> I have no idea why Travis fails when recreating the database all of the sudden...

Seems to be a models issue, same problem here: https://github.com/ontohub/ontohub-models/pull/166

**Comment by phyrog** [comment]
I'm quite certain it's the update of `sequel-rails` from `1.0.0` to `1.0.1`. All the branches that update this fail.

**Comment by phyrog** [comment]
Should be fixed after merging ontohub/ontohub-models#162

**Comment by eugenk** [comment]
Done

**Comment by eugenk** [comment]
Where was `new_record?` defined? I thought Sequel's method is simply called `new?`

**Comment by phyrog** [comment]
I think if you update the models once more, this should be good.

**Pull request merged**
