### PR TITLE
Add RabbitMQ prefix and exchange options

### PR DESCRIPTION
**Pull request by eugenk**
This shall add prefix and exchange options for RabbitMQ. Queue names will be prefixed and the exchange will be chosen by the app. This is needed for the system-tests to not interfere with the backend seeds because the queues are emptied in the seeds (and they run in the system-tests).

This pull request is blocked because of #343: It still needs to validate the settings.

### CODE REVIEW

**Comment by eugenk** [comment]
ping

**Comment by phyrog** [comment]
Once the new settings key is validated :+1:

**Comment by eugenk** [comment]
Well, we have a circular dependency:

settings_schema.rb:
```ruby
Dir.glob('app/workers/*.rb').sort.each do |file|
  require_relative Rails.root.join(file).to_s
end
```

application_worker.rb:
```ruby
class ApplicationWorker
  ...  
  from_queue "#{Settings.rabbitmq.prefix}_default"
```

**Comment by phyrog** [comment]
Yikes. We could possibly hack something into `settings_schema.rb` to not load the files, but look at the file name and define an empty class for each of the files which are reopened when loading the worker files.

**Comment by eugenk** [comment]
I think that's too complicated. A simple list of allowed values (maintained by us) should suffice. There won't be that many workers.

**Comment by eugenk** [comment]
Done. It's ready for review

**Pull request merged**
